### PR TITLE
Missing stuff

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because there is no other branch.

## Changelog

```markdown
### Added
- Added missing base entities

### Fixed
 - Fixed PHPUnit config
```

## Subject

Some dev update for the first stable.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
screenshot 2017-10-02 07 28 27

Why are merge commits not allowed?

**Comment by core23** [comment]
@OskarStark Changed the repo settings. Please try again

**Comment by OskarStark** [comment]
> @OskarStark Changed the repo settings. Please try again

Thank you, the same problem occured on Authenticator repo

**Comment by greg0ire** [comment]
@Soullivaneuh changed this so that we use rebase.

**Comment by jlamur** [comment]
@core23 @OskarStark You don't want to follow my advice then? :cry: https://github.com/sonata-project/dev-kit/pull/289

**Comment by core23** [comment]
Sorry, I misted the change at the contribution docs

**Pull request merged**
